## Line Up
| Slot | From   | To     | Length | Format           | Speaker(s)                         | Title/Abstract                                                                                                                   | Email                   |
|------|--------|--------|--------|------------------|-------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------|-------------------------|
| 0    | 13:10  | 13:15  | 0:05   | Intro            | Hosts                              | Intro                                                                                                                             |                         |
| 1    | 13:15  | 13:25  | 0:10   | Lightning Talk   | Axel Thévenet                      | OSOR Handbook on Open Source Software in Public Administration                                                                    |                         |
|      | 13:25  | 13:30  | 0:05   | Transition       |                                     |                                                                                                                                   |                         |
| 2    | 13:30  | 13:40  | 0:10   | Lightning Talk   | Johan Linåker                      | How is Development and Collaboration Done in Public Sector Open Source Software Projects? Insights from Six Mature Case Studies   |                         |
|      | 13:40  | 13:45  | 0:05   | Transition       |                                     |                                                                                                                                   |                         |
| 3    | 13:45  | 14:10  | 0:25   | 25-minute Talk   | Leonhard Kugler                    | openDesk on openCode: Developing a Secure Office Suite and SDLC                                                                   |                         |
|      | 14:10  | 14:15  | 0:05   | Transition       |                                     |                                                                                                                                   |                         |
| 4    | 14:15  | 14:45  | 0:30   | 30-minute Talk   | Ludovic Dubost, Michael Meeks, Frank Karlitschek, Amandine Le Pape, Tilman Kranz, Stefan Bogner, René Fischer | Roundtable openDesk: Discussions on governments collaborating with Open Source vendors, data sovereignty, and shared environments |                         |
|      | 14:45  | 14:50  | 0:05   | Transition       |                                     |                                                                                                                                   |                         |
| 5    | 14:50  | 15:15  | 0:25   | 25-minute Talk   | Alexander Smolianitski, Virgile Deville | Note-Worthy Collaboration: Co-developing a Note-Taking Application                                                               |                         |
|      | 15:15  | 15:20  | 0:05   | Transition       |                                     |                                                                                                                                   |                         |
| 6    | 15:20  | 15:45  | 0:25   | 25-minute Talk   | Thierry Carrez, Louis Vigneras     | Nubo: The French Government Sovereign Cloud                                                                                      |                         |
|      | 15:45  | 15:50  | 0:05   | Transition       |                                     |                                                                                                                                   |                         |
| 7    | 15:50  | 16:00  | 0:10   | Lightning Talk   | Kurt Garloff, Nico Lueck           | GovStack Cloud BB: Sovereign Clouds for all countries                                                                            |                         |
|      | 16:00  | 16:05  | 0:05   | Transition       |                                     |                                                                                                                                   |                         |
| 8    | 16:05  | 16:30  | 0:25   | 25-minute Talk   | Bianca Kastl                       | Building Open Digital Infrastructures for Public Health                                                                          |                         |
|      | 16:30  | 16:35  | 0:05   | Transition       |                                     |                                                                                                                                   |                         |
| 9    | 16:35  | 16:45  | 0:10   | Lightning Talk   | Nil Homedes                        | FLOSS as a Public Policy: The Case of Decidim                                                                                   |                         |
|      | 16:45  | 16:50  | 0:05   | Outro            | Hosts                              | Outro                                                                                                                             |                         |
